// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: currency_converter.proto
// Protobuf Java Version: 4.28.2

package proto;

/**
 * Protobuf type {@code proto.ConvertRequest}
 */
public final class ConvertRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.ConvertRequest)
    ConvertRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ConvertRequest.class.getName());
  }
  // Use ConvertRequest.newBuilder() to construct.
  private ConvertRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ConvertRequest() {
    sourceCurrency_ = "";
    targetCurrency_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.CurrencyConverterOuterClass.internal_static_proto_ConvertRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.CurrencyConverterOuterClass.internal_static_proto_ConvertRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.ConvertRequest.class, proto.ConvertRequest.Builder.class);
  }

  public static final int AMOUNT_FIELD_NUMBER = 1;
  private double amount_ = 0D;
  /**
   * <code>double amount = 1;</code>
   * @return The amount.
   */
  @java.lang.Override
  public double getAmount() {
    return amount_;
  }

  public static final int SOURCE_CURRENCY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceCurrency_ = "";
  /**
   * <code>string source_currency = 2;</code>
   * @return The sourceCurrency.
   */
  @java.lang.Override
  public java.lang.String getSourceCurrency() {
    java.lang.Object ref = sourceCurrency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceCurrency_ = s;
      return s;
    }
  }
  /**
   * <code>string source_currency = 2;</code>
   * @return The bytes for sourceCurrency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceCurrencyBytes() {
    java.lang.Object ref = sourceCurrency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_CURRENCY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object targetCurrency_ = "";
  /**
   * <code>string target_currency = 3;</code>
   * @return The targetCurrency.
   */
  @java.lang.Override
  public java.lang.String getTargetCurrency() {
    java.lang.Object ref = targetCurrency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetCurrency_ = s;
      return s;
    }
  }
  /**
   * <code>string target_currency = 3;</code>
   * @return The bytes for targetCurrency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetCurrencyBytes() {
    java.lang.Object ref = targetCurrency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      output.writeDouble(1, amount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceCurrency_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sourceCurrency_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetCurrency_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, targetCurrency_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, amount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceCurrency_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sourceCurrency_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetCurrency_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, targetCurrency_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.ConvertRequest)) {
      return super.equals(obj);
    }
    proto.ConvertRequest other = (proto.ConvertRequest) obj;

    if (java.lang.Double.doubleToLongBits(getAmount())
        != java.lang.Double.doubleToLongBits(
            other.getAmount())) return false;
    if (!getSourceCurrency()
        .equals(other.getSourceCurrency())) return false;
    if (!getTargetCurrency()
        .equals(other.getTargetCurrency())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    hash = (37 * hash) + SOURCE_CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getSourceCurrency().hashCode();
    hash = (37 * hash) + TARGET_CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getTargetCurrency().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.ConvertRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ConvertRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ConvertRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ConvertRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ConvertRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ConvertRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ConvertRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.ConvertRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.ConvertRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.ConvertRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.ConvertRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.ConvertRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.ConvertRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.ConvertRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.ConvertRequest)
      proto.ConvertRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.CurrencyConverterOuterClass.internal_static_proto_ConvertRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.CurrencyConverterOuterClass.internal_static_proto_ConvertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ConvertRequest.class, proto.ConvertRequest.Builder.class);
    }

    // Construct using proto.ConvertRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      amount_ = 0D;
      sourceCurrency_ = "";
      targetCurrency_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.CurrencyConverterOuterClass.internal_static_proto_ConvertRequest_descriptor;
    }

    @java.lang.Override
    public proto.ConvertRequest getDefaultInstanceForType() {
      return proto.ConvertRequest.getDefaultInstance();
    }

    @java.lang.Override
    public proto.ConvertRequest build() {
      proto.ConvertRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.ConvertRequest buildPartial() {
      proto.ConvertRequest result = new proto.ConvertRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(proto.ConvertRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sourceCurrency_ = sourceCurrency_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.targetCurrency_ = targetCurrency_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.ConvertRequest) {
        return mergeFrom((proto.ConvertRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.ConvertRequest other) {
      if (other == proto.ConvertRequest.getDefaultInstance()) return this;
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      if (!other.getSourceCurrency().isEmpty()) {
        sourceCurrency_ = other.sourceCurrency_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTargetCurrency().isEmpty()) {
        targetCurrency_ = other.targetCurrency_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              amount_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 18: {
              sourceCurrency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              targetCurrency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double amount_ ;
    /**
     * <code>double amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 1;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(double value) {

      amount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      amount_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object sourceCurrency_ = "";
    /**
     * <code>string source_currency = 2;</code>
     * @return The sourceCurrency.
     */
    public java.lang.String getSourceCurrency() {
      java.lang.Object ref = sourceCurrency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceCurrency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_currency = 2;</code>
     * @return The bytes for sourceCurrency.
     */
    public com.google.protobuf.ByteString
        getSourceCurrencyBytes() {
      java.lang.Object ref = sourceCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_currency = 2;</code>
     * @param value The sourceCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setSourceCurrency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceCurrency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string source_currency = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceCurrency() {
      sourceCurrency_ = getDefaultInstance().getSourceCurrency();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string source_currency = 2;</code>
     * @param value The bytes for sourceCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setSourceCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceCurrency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object targetCurrency_ = "";
    /**
     * <code>string target_currency = 3;</code>
     * @return The targetCurrency.
     */
    public java.lang.String getTargetCurrency() {
      java.lang.Object ref = targetCurrency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetCurrency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target_currency = 3;</code>
     * @return The bytes for targetCurrency.
     */
    public com.google.protobuf.ByteString
        getTargetCurrencyBytes() {
      java.lang.Object ref = targetCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target_currency = 3;</code>
     * @param value The targetCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setTargetCurrency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      targetCurrency_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string target_currency = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetCurrency() {
      targetCurrency_ = getDefaultInstance().getTargetCurrency();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string target_currency = 3;</code>
     * @param value The bytes for targetCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setTargetCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      targetCurrency_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.ConvertRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.ConvertRequest)
  private static final proto.ConvertRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.ConvertRequest();
  }

  public static proto.ConvertRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConvertRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConvertRequest>() {
    @java.lang.Override
    public ConvertRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConvertRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConvertRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.ConvertRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

