// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: currency_converter.proto
// Protobuf Java Version: 4.28.2

package proto;

public interface ConvertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ConvertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double amount = 1;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>string source_currency = 2;</code>
   * @return The sourceCurrency.
   */
  java.lang.String getSourceCurrency();
  /**
   * <code>string source_currency = 2;</code>
   * @return The bytes for sourceCurrency.
   */
  com.google.protobuf.ByteString
      getSourceCurrencyBytes();

  /**
   * <code>string target_currency = 3;</code>
   * @return The targetCurrency.
   */
  java.lang.String getTargetCurrency();
  /**
   * <code>string target_currency = 3;</code>
   * @return The bytes for targetCurrency.
   */
  com.google.protobuf.ByteString
      getTargetCurrencyBytes();
}
