// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: currency_converter.proto
// Protobuf Java Version: 4.28.2

package proto;

public interface ConvertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ConvertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double converted_amount = 1;</code>
   * @return The convertedAmount.
   */
  double getConvertedAmount();
}
