// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: currency_converter.proto
// Protobuf Java Version: 4.28.2

package proto;

public final class CurrencyConverterOuterClass {
  private CurrencyConverterOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      CurrencyConverterOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ConvertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ConvertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ConvertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ConvertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030currency_converter.proto\022\005proto\"R\n\016Con" +
      "vertRequest\022\016\n\006amount\030\001 \001(\001\022\027\n\017source_cu" +
      "rrency\030\002 \001(\t\022\027\n\017target_currency\030\003 \001(\t\"+\n" +
      "\017ConvertResponse\022\030\n\020converted_amount\030\001 \001" +
      "(\0012M\n\021CurrencyConverter\0228\n\007Convert\022\025.pro" +
      "to.ConvertRequest\032\026.proto.ConvertRespons" +
      "eB\013P\001Z\007./protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_ConvertRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ConvertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ConvertRequest_descriptor,
        new java.lang.String[] { "Amount", "SourceCurrency", "TargetCurrency", });
    internal_static_proto_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ConvertResponse_descriptor,
        new java.lang.String[] { "ConvertedAmount", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
